import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        primary: "#c0c1ff",
        "primary-container": "#8083ff",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        secondary: "#5de6ff",
        "secondary-container": "#00cbe6",
        "secondary-fixed": "#a2eeff",
        "secondary-fixed-dim": "#2fd9f4",
        tertiary: "#ffb2b7",
        "tertiary-container": "#ff516a",
        "tertiary-fixed": "#ffdadb",
        "tertiary-fixed-dim": "#ffb2b7",
        error: "#ffb4ab",
        "error-container": "#93000a",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c7c4d7",
        "on-primary": "#1000a9",
        "on-primary-container": "#0d0096",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#00363e",
        "on-secondary-container": "#00515d",
        "on-secondary-fixed": "#001f25",
        "on-secondary-fixed-variant": "#004e5a",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#494bd6",
        "surface-tint": "#c0c1ff",
      },
      fontFamily: {
        body: ["var(--font-inter)", "sans-serif"],
        heading: ["var(--font-geist)", "sans-serif"],
        brush: ["var(--font-brush)", "cursive"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        gutter: "24px",
        lg: "48px",
        xl: "80px",
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;